name: cyber_snake
description: A cyber-themed snake game built with Flutter.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.18.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  audioplayers: ^5.2.1 # ✅ Für Sound

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/beep.wav
    - assets/sounds/beep_high.wav
    - assets/sounds/beep_low.wav
    - assets/images/mouse.png
    - assets/images/frog.png